### ISSUE TITLE
Difference from `eslint-plugin-import` rule

### ISSUE THREAD

**Issue by brettz9** [cybersemics/eslint-plugin-export-default-identifier#1]
Hi,

Just thought you might want to distinguish how this differs--if it differs--from the rule within [`eslint-plugin-import`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-anonymous-default-export.md) even if it is only to be for the purpose that it avoids the need for the rest of the `eslint-plugin-import` plugin being imported.

**Comment by raineorshine** [comment]
Thanks! I wasn't aware of that rule in `eslint-plugin-import`.
